#!/bin/bash
# Скрипт для вывода ВСЕХ параметров LibreSDR B210 из дерева
# Использование: ./show_b210_specs.sh [serial]

SERIAL="${1:-DW49CI6}"
ARGS="serial=$SERIAL"

echo "=================================================="
echo "  LibreSDR B210 - ВСЕ параметры устройства"
echo "=================================================="
echo ""
echo "Считываем полное дерево параметров..."
echo ""

# Функция для получения значения параметра
get_param() {
    local path="$1"
    local value=$(uhd_usrp_probe --args="$ARGS" --string="$path" 2>/dev/null)
    echo "$value"
}

# Получаем дерево путей
TREE=$(uhd_usrp_probe --args="$ARGS" --tree 2>/dev/null)

echo "=================================================="
echo "📋 БАЗОВАЯ ИНФОРМАЦИЯ"
echo "=================================================="
echo "  Serial: $SERIAL"
echo "  Name: $(get_param /mboards/0/name)"
echo "  Codename: $(get_param /mboards/0/codename)"
echo "  FW Version: $(get_param /mboards/0/fw_version)"
echo "  FPGA Version: $(get_param /mboards/0/fpga_version)"
echo "  USB Version: $(get_param /mboards/0/usb_version)"
echo "  Link Max Rate: $(get_param /mboards/0/link_max_rate)"
echo ""

echo "=================================================="
echo "⏱️  СИНХРОНИЗАЦИЯ И ТАКТИРОВАНИЕ"
echo "=================================================="
echo "  Tick Rate: $(get_param /mboards/0/tick_rate)"
echo "  Tick Rate Range: $(get_param /mboards/0/tick_rate/range)"
echo "  Auto Tick Rate: $(get_param /mboards/0/auto_tick_rate)"
echo ""
echo "Clock Source:"
echo "  Current: $(get_param /mboards/0/clock_source/value)"
echo "  Options: $(get_param /mboards/0/clock_source/options)"
echo ""
echo "Time Source:"
echo "  Current: $(get_param /mboards/0/time_source/value)"
echo "  Options: $(get_param /mboards/0/time_source/options)"
echo ""

echo "=================================================="
echo "📡 TX FRONTEND A (Передатчик, канал 1)"
echo "=================================================="
echo "  Name: $(get_param /mboards/0/dboards/A/tx_frontends/A/name)"
echo ""
echo "Frequency:"
echo "  Range: $(get_param /mboards/0/dboards/A/tx_frontends/A/freq/range)"
echo "  Current: $(get_param /mboards/0/dboards/A/tx_frontends/A/freq/value)"
echo ""
echo "Gain:"
echo "  PGA Range: $(get_param /mboards/0/dboards/A/tx_frontends/A/gains/PGA/range)"
echo "  PGA Value: $(get_param /mboards/0/dboards/A/tx_frontends/A/gains/PGA/value)"
echo ""
echo "Bandwidth:"
echo "  Range: $(get_param /mboards/0/dboards/A/tx_frontends/A/bandwidth/range)"
echo "  Current: $(get_param /mboards/0/dboards/A/tx_frontends/A/bandwidth/value)"
echo ""
echo "Antenna:"
echo "  Current: $(get_param /mboards/0/dboards/A/tx_frontends/A/antenna/value)"
echo "  Options: $(get_param /mboards/0/dboards/A/tx_frontends/A/antenna/options)"
echo ""
echo "Other:"
echo "  Connection: $(get_param /mboards/0/dboards/A/tx_frontends/A/connection)"
echo "  Enabled: $(get_param /mboards/0/dboards/A/tx_frontends/A/enabled)"
echo "  Use LO Offset: $(get_param /mboards/0/dboards/A/tx_frontends/A/use_lo_offset)"
echo ""
echo "Filters:"
echo "  FIR_1: $(get_param /mboards/0/dboards/A/tx_frontends/A/filters/FIR_1/value)"
echo "  HB_1: $(get_param /mboards/0/dboards/A/tx_frontends/A/filters/HB_1/value)"
echo "  HB_2: $(get_param /mboards/0/dboards/A/tx_frontends/A/filters/HB_2/value)"
echo "  HB_3: $(get_param /mboards/0/dboards/A/tx_frontends/A/filters/HB_3/value)"
echo "  INT_3: $(get_param /mboards/0/dboards/A/tx_frontends/A/filters/INT_3/value)"
echo "  LPF_BB: $(get_param /mboards/0/dboards/A/tx_frontends/A/filters/LPF_BB/value)"
echo "  LPF_SECONDARY: $(get_param /mboards/0/dboards/A/tx_frontends/A/filters/LPF_SECONDARY/value)"
echo ""

echo "=================================================="
echo "📡 TX FRONTEND B (Передатчик, канал 2)"
echo "=================================================="
echo "  Name: $(get_param /mboards/0/dboards/A/tx_frontends/B/name)"
echo "  Freq Range: $(get_param /mboards/0/dboards/A/tx_frontends/B/freq/range)"
echo "  Gain Range: $(get_param /mboards/0/dboards/A/tx_frontends/B/gains/PGA/range)"
echo "  BW Range: $(get_param /mboards/0/dboards/A/tx_frontends/B/bandwidth/range)"
echo "  Antenna Options: $(get_param /mboards/0/dboards/A/tx_frontends/B/antenna/options)"
echo ""

echo "=================================================="
echo "📻 RX FRONTEND A (Приёмник, канал 1)"
echo "=================================================="
echo "  Name: $(get_param /mboards/0/dboards/A/rx_frontends/A/name)"
echo ""
echo "Frequency:"
echo "  Range: $(get_param /mboards/0/dboards/A/rx_frontends/A/freq/range)"
echo "  Current: $(get_param /mboards/0/dboards/A/rx_frontends/A/freq/value)"
echo ""
echo "Gain:"
echo "  PGA Range: $(get_param /mboards/0/dboards/A/rx_frontends/A/gains/PGA/range)"
echo "  PGA Value: $(get_param /mboards/0/dboards/A/rx_frontends/A/gains/PGA/value)"
echo ""
echo "Bandwidth:"
echo "  Range: $(get_param /mboards/0/dboards/A/rx_frontends/A/bandwidth/range)"
echo "  Current: $(get_param /mboards/0/dboards/A/rx_frontends/A/bandwidth/value)"
echo ""
echo "Antenna:"
echo "  Current: $(get_param /mboards/0/dboards/A/rx_frontends/A/antenna/value)"
echo "  Options: $(get_param /mboards/0/dboards/A/rx_frontends/A/antenna/options)"
echo ""
echo "AGC (Автоматическая регулировка усиления):"
echo "  Enable: $(get_param /mboards/0/dboards/A/rx_frontends/A/gain/agc/enable)"
echo "  Mode: $(get_param /mboards/0/dboards/A/rx_frontends/A/gain/agc/mode/value)"
echo "  Mode Options: $(get_param /mboards/0/dboards/A/rx_frontends/A/gain/agc/mode/options)"
echo ""
echo "DC Offset & IQ Balance:"
echo "  DC Offset Enable: $(get_param /mboards/0/dboards/A/rx_frontends/A/dc_offset/enable)"
echo "  IQ Balance Enable: $(get_param /mboards/0/dboards/A/rx_frontends/A/iq_balance/enable)"
echo ""
echo "Filters:"
echo "  FIR_1: $(get_param /mboards/0/dboards/A/rx_frontends/A/filters/FIR_1/value)"
echo "  HB_1: $(get_param /mboards/0/dboards/A/rx_frontends/A/filters/HB_1/value)"
echo "  HB_2: $(get_param /mboards/0/dboards/A/rx_frontends/A/filters/HB_2/value)"
echo "  HB_3: $(get_param /mboards/0/dboards/A/rx_frontends/A/filters/HB_3/value)"
echo "  DEC_3: $(get_param /mboards/0/dboards/A/rx_frontends/A/filters/DEC_3/value)"
echo "  LPF_BB: $(get_param /mboards/0/dboards/A/rx_frontends/A/filters/LPF_BB/value)"
echo "  LPF_TIA: $(get_param /mboards/0/dboards/A/rx_frontends/A/filters/LPF_TIA/value)"
echo ""

echo "=================================================="
echo "📻 RX FRONTEND B (Приёмник, канал 2)"
echo "=================================================="
echo "  Name: $(get_param /mboards/0/dboards/A/rx_frontends/B/name)"
echo "  Freq Range: $(get_param /mboards/0/dboards/A/rx_frontends/B/freq/range)"
echo "  Gain Range: $(get_param /mboards/0/dboards/A/rx_frontends/B/gains/PGA/range)"
echo "  BW Range: $(get_param /mboards/0/dboards/A/rx_frontends/B/bandwidth/range)"
echo "  Antenna Options: $(get_param /mboards/0/dboards/A/rx_frontends/B/antenna/options)"
echo "  AGC Options: $(get_param /mboards/0/dboards/A/rx_frontends/B/gain/agc/mode/options)"
echo ""

echo "=================================================="
echo "⚙️  DSP (RX)"
echo "=================================================="
echo "RX DSP 0:"
echo "  Rate Range: $(get_param /mboards/0/rx_dsps/0/rate/range)"
echo "  Rate Value: $(get_param /mboards/0/rx_dsps/0/rate/value)"
echo "  Freq Range: $(get_param /mboards/0/rx_dsps/0/freq/range)"
echo "  Freq Value: $(get_param /mboards/0/rx_dsps/0/freq/value)"
echo ""
echo "RX DSP 1:"
echo "  Rate Range: $(get_param /mboards/0/rx_dsps/1/rate/range)"
echo "  Freq Range: $(get_param /mboards/0/rx_dsps/1/freq/range)"
echo ""

echo "=================================================="
echo "⚙️  DSP (TX)"
echo "=================================================="
echo "TX DSP 0:"
echo "  Rate Range: $(get_param /mboards/0/tx_dsps/0/rate/range)"
echo "  Rate Value: $(get_param /mboards/0/tx_dsps/0/rate/value)"
echo "  Freq Range: $(get_param /mboards/0/tx_dsps/0/freq/range)"
echo "  Freq Value: $(get_param /mboards/0/tx_dsps/0/freq/value)"
echo ""
echo "TX DSP 1:"
echo "  Rate Range: $(get_param /mboards/0/tx_dsps/1/rate/range)"
echo "  Freq Range: $(get_param /mboards/0/tx_dsps/1/freq/range)"
echo ""

echo "=================================================="
echo "🔌 CODECS"
echo "=================================================="
echo "RX Codec A:"
echo "  Name: $(get_param /mboards/0/rx_codecs/A/name)"
echo ""
echo "TX Codec A:"
echo "  Name: $(get_param /mboards/0/tx_codecs/A/name)"
echo ""

echo "=================================================="
echo "🌡️  СЕНСОРЫ"
echo "=================================================="
echo "Mboard Sensors:"
echo "  ref_locked: $(get_param /mboards/0/sensors/ref_locked)"
echo ""

echo "=================================================="
echo "📊 КАНАЛЫ И МАППИНГ"
echo "=================================================="
echo "  RX Chan DSP Mapping: $(get_param /mboards/0/rx_chan_dsp_mapping)"
echo "  TX Chan DSP Mapping: $(get_param /mboards/0/tx_chan_dsp_mapping)"
echo "  RX Subdev Spec: $(get_param /mboards/0/rx_subdev_spec)"
echo "  TX Subdev Spec: $(get_param /mboards/0/tx_subdev_spec)"
echo ""

echo "=================================================="
echo "  ИТОГО: 2x2 MIMO (2 TX + 2 RX)"
echo "  LibreSDR патч: Активен"
echo "=================================================="
